### ISSUE TITLE
Comparison with django-zxcvbn-password

### ISSUE THREAD

**Issue by pawamoy** [Pierre-Sassoulas/django-zxcvbn-password-validator#4]
Hi, just saw your project and it seems good :slightly_smiling_face: 

I was wondering: is it compatible with [django-zxcvbn-password](https://github.com/pawamoy/django-zxcvbn-password) (disclaimer: I made it). Did you know it existed? If yes, why did you choose to make your own?

The thing is, I was never quite satisfied with mine (it is the combination of two other django apps), so I wonder if, now that I don't have so much time to maintain it, I should redirect people to your app.

**Comment by Pierre-Sassoulas** [comment]
Hi @pawamoy, thank you for the kind words, greatly appreciated !

I remember checking the other apps before making mine, but I don't remember everything that went into the decision. I think I wanted something really simple at the time, using the most default values possible and the least dependencies possible. So I wanted to be based directly upon the python port of zxcvbn, in order to minimize dependencies that could introduce problem with password handling that is critical in term of security. As a matter of fact I have a lot less features than what you have (in fact I just have a PasswordValidator). So my project is probably compatible with everything you did as long as `zxcvbn_password.ZXCVBNValidator` can be replaced by my password validator. You seem to have options given as parameters in the declaration, I'm not sure I can handle that.

**Comment by pawamoy** [comment]
Okay so yours "just" do backend validation. I think its the main difference. I indeed like your minimalistic approach! And you have tests :sparkles: :scream_cat: :sparkles:

I think I'm still gonna link your app in my README (and don't feel obliged to reciprocate!)
